[2023-12-11 22:02:56,392] INFO _log() L96   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.0.0.126:5000 - call_trace=Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 22:02:56,395] INFO _log() L96   [33mPress CTRL+C to quit[0m - call_trace=Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 22:02:56,397] INFO _log() L96    * Restarting with stat - call_trace=Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 22:03:01,217] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 22:03:01] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 22:03:01,284] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 22:03:01] "GET /openapi/ HTTP/1.1" 200 - - call_trace=Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 22:03:01,677] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 22:03:01] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 22:03:01,700] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 22:03:01] "[36mGET /openapi/static/images/redoc.svg HTTP/1.1[0m" 304 - - call_trace=Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 22:03:01,780] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 22:03:01] "[36mGET /openapi/static/images/rapidoc.svg HTTP/1.1[0m" 304 - - call_trace=Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 22:03:02,545] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 22:03:02] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 22:03:02,563] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 22:03:02] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 22:03:02,564] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 22:03:02] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 22:03:02,565] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 22:03:02] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 22:03:02,915] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 22:03:02] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 22:03:11,151] ERROR log_exception() L825  Exception on /amostra [POST] - call_trace=Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\flask\app.py L825 
Traceback (most recent call last):
  File "Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\flask_openapi3\scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "Z:\ENEM\exemplo_mvp\api\app.py", line 77, in predict
    outcome=Model.preditor (modelo, form)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\ENEM\exemplo_mvp\api\model\modelo.py", line 24, in preditor
    form.Hardness,
    ^^^^^^^^^^^^^
  File "Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\pydantic\main.py", line 761, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'AmostraSchema' object has no attribute 'Hardness'
[2023-12-11 22:03:11,158] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 22:03:11] "[35m[1mPOST /amostra HTTP/1.1[0m" 500 - - call_trace=Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 22:04:34,779] INFO _log() L96    * Detected change in 'Z:\\ENEM\\exemplo_mvp\\api\\model\\modelo.py', reloading - call_trace=Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 22:04:35,015] INFO _log() L96    * Restarting with stat - call_trace=Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 22:04:41,497] ERROR log_exception() L825  Exception on /amostra [POST] - call_trace=Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\flask\app.py L825 
Traceback (most recent call last):
  File "Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\flask_openapi3\scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "Z:\ENEM\exemplo_mvp\api\app.py", line 65, in predict
    amostra = Amostra(
              ^^^^^^^^
TypeError: __init__() got an unexpected keyword argument 'Hardness'
[2023-12-11 22:04:41,508] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 22:04:41] "[35m[1mPOST /amostra HTTP/1.1[0m" 500 - - call_trace=Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 22:06:45,627] INFO _log() L96    * Detected change in 'Z:\\ENEM\\exemplo_mvp\\api\\app.py', reloading - call_trace=Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 22:06:45,861] INFO _log() L96    * Restarting with stat - call_trace=Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 22:07:11,390] WARNING predict() L105  Erro ao adicionar amostra '10', Não foi possível salvar novo item :/ - call_trace=Z:\ENEM\exemplo_mvp\api\app.py L105 
[2023-12-11 22:07:11,391] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 22:07:11] "[31m[1mPOST /amostra HTTP/1.1[0m" 400 - - call_trace=Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 23:23:03,117] WARNING get_amostras() L45   Não há amostras cadastrados na base :/ - call_trace=Z:\ENEM\exemplo_mvp\api\app.py L45  
[2023-12-11 23:23:03,120] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 23:23:03] "[33mGET /amostras HTTP/1.1[0m" 404 - - call_trace=Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 23:23:37,883] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 23:23:37] "[31m[1mGET /amostra?numero= HTTP/1.1[0m" 422 - - call_trace=Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 23:23:37,940] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 23:23:37] "[31m[1mPOST /amostra HTTP/1.1[0m" 422 - - call_trace=Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 23:23:43,129] WARNING get_amostras() L45   Não há amostras cadastrados na base :/ - call_trace=Z:\ENEM\exemplo_mvp\api\app.py L45  
[2023-12-11 23:23:43,131] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 23:23:43] "[33mGET /amostras HTTP/1.1[0m" 404 - - call_trace=Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 23:26:23,682] WARNING get_amostras() L45   Não há amostras cadastrados na base :/ - call_trace=Z:\ENEM\exemplo_mvp\api\app.py L45  
[2023-12-11 23:26:23,684] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 23:26:23] "[33mGET /amostras HTTP/1.1[0m" 404 - - call_trace=Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 23:26:37,701] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 23:26:37] "[31m[1mGET /amostra?numero= HTTP/1.1[0m" 422 - - call_trace=Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\werkzeug\_internal.py L96  
